sudo: false
language: erlang
notifications:
  email:
    recipients: pms.lopes@campus.fct.unl.pt
    on_success: never
    on_failure: always
otp_release:
  - 21.0
install:
  - make compile
  - make release
before_script:
  - epmd -daemon
script:
  - make test
  - make ct
after_success:
  - bin/covertool -cover _build/test/cover/eunit.coverdata -appname aql -output cover.xml
  - codecov
branches:
  only:
  - master
